apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-back-despachos
  namespace: innovatech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-despachos
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-back-ventas
  namespace: innovatech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-ventas
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-frontend
  namespace: innovatech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-despacho
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
